#include<bits/stdc++.h>
using namespace std;
#define ll long long
#define MAXN 500005
int n;
vector<ll>a;

ll fun()
{

}
int main()
{
    ios::sync_with_stdio(false); cin.tie(0); cout.tie(0);

    cin>>n;

    a.clear();

    for(int i=0; i<n; i++){
        ll x; cin>>x;
        a.push_back(x);
    }

    ll ans = fun();

    cout << ans << endl;

    //main();
    return 0;
}


